language: node_js

node_js: '8.10'

install: npm install

script:
  - npm run test && npm run coverage

before_deploy:
  - npm run build
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then BRANCH='dev'; else BRANCH='master'; fi;

deploy:
  provider: "lambda"
  function_name: "cognicity-telegram-webhook-$BRANCH"
  region: $AWS_REGION
  role: $AWS_LAMBDA_ROLE
  runtime: "nodejs8.10"
  module_name: "bin/functions/notify/index"
  handler_name: "default"

