language: node_js

node_js: '8.10'

install: npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy: 
  provider: lambda
  function_name: "cognicity-telegram-webhook-dev"
  region: $AWS_REGION
  role: $AWS_LAMBDA_ROLE
  runtime: "nodejs8.10"
  module_name: "bin/functions/receive/index"
  handler_name: "default"
  on:
    branch: dev

