language: node_js

node_js: '8.10'

install: npm install

script:
  - npm run test && npm run coverage

before_deploy:
  - npm run build

deploy: 
  - provider: lambda
    function_name: "cognicity-telegram-webhook-dev"
    region: $AWS_REGION
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/receive"
    handler_name: "default"
    on:
      branch: dev 
  - provider: lambda
    function_name: "cognicity-telegram-reply-dev"
    region: $AWS_REGION
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/send"
    handler_name: "default"
    on:
      branch: dev
  - provider: lambda
    function_name: "cognicity-telegram-webhook-prod"
    region: $AWS_REGION
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/receive"
    handler_name: "default"
    on:
      branch: master 
  - provider: lambda
    function_name: "cognicity-telegram-reply-prod"
    region: $AWS_REGION
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/send"
    handler_name: "default"
    on:
      branch: master

